### ISSUE TITLE
Duplicate assignment of self.username

### ISSUE THREAD

**Issue by Kane610** [balloob/aiohue#11]
https://github.com/balloob/aiohue/blob/9337988089d9d9ce6e182e0145f5663642a9562a/aiohue/bridge.py#L20

**Comment by balloob** [comment]
It took you more time to write this issue than it would have taken to fix it 😉

**Comment by Kane610** [comment]
I tried the direkt report in github for the first time 👍🏻😎

**Comment by balloob** [comment]
Oh interesting, didn't know that was possible. I always create them manually by pressing `y` to convert the page to a perma-link, which is embeddable.

**Comment by Kane610** [comment]
Yeah, I don't know how long that feature was there before I saw it. Yay for incremental updates!
