### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by domibarton** [balloob/aiohue#17]
As I'm currently struggling with this HASS [Issue](https://github.com/home-assistant/home-assistant/issues/13389) / [PR](https://github.com/home-assistant/home-assistant/pull/22645), I had a look at the exception handling.

I saw you catch the origin `aiohttp.client_exceptions.ClientError` in your [`bridge.py`](https://github.com/balloob/aiohue/blob/master/aiohue/bridge.py#L66-L69). That's a nice idea, but IMHO that could be improved / optimized quite a bit, because:

- Currently all `aiohttp` Exceptions will just be wrapped into a single `aiohue.RequestError`, as `aiohttp.client_exceptions.ClientError` is the base class for all `aiohttp.client_exceptions`.
- Thus, specific `aiohttp` exceptions are lost and all merged into a single exception. That's not very "pythonic" (explicit is better than implicit) and I think there's a reason why `aiohttp` is raising all those different exceptions.
- The origin exceptions have much more informations than your `RequestError`, thus giving the developer more context to handle the exception.
- You're doing a `raise RequestError(…) from None`. Is there a reason why it is `from None` instead `from err`, because that would probably a good usecase for it.

Long story, short: By merging all the different `aiohttp` exceptions into a single one without using the proper `raise… from…` syntax, you'll end up with:

- Missing the *real* cause of the exception (because `raise… from…` isn't "properly" used)
- Less context (missing informations which just will be thrown away in the wrapper)
- Less leverage in exception handling (only a single exception type)

Would it be possible to just raise the origin exception, or at least use the proper `raise… from…` syntax?

I didn't want to offend you in any way ;) I think there might be also a reason why you've decided that way. Just thought I'll address it here. Thanks anyway for your awesome lib!!!

**Comment by balloob** [comment]
Leaking aiohttp errors feels like leaking implementation details. 

What use case do you have where you want to differentiate between request errors?

**Comment by domibarton** [comment]
Ehrm isn't that the whole point of exceptions, "leaking" details about the occurred error to the caller? :)

There are always a couple of reasons / use cases where you want as much details as possible, at least from a *caller point of view*. Of course, the *human user* which reads the logfile is fine with a simple string, but as a developer I want to do exception handling programmatically, thus relating to different / explicit exception classes and attributes (such as the status code in this case).

I always leave it to the caller what he/she wants to do with the occured error. Therefore, I usually won't intercept exceptions, or interfere existing exceptions in my code. The only exception (hah pun ^^) is, when I expect some erroneous behaviour which I've to handle explicitly on my side. But I wouldn't simply wrap a bunch of exceptions into a single one. Instead, I'd create my own base exception (derived from `Exception`) and use class inheritance for all my sub-classes/sub-exceptions.

If you want a proper interface and "hide internals" (such as in this case), then I'd make sure that at least all relevant details are included in the new exception. But here's the tricky part: What's relevant? Ask 10 developers and you might get 10 different answers, because that question is highly subjectiv. 

Because of that, I'd make sure ALL the details are included and leave this decision to the developer implementing my code/module/lib, as I won't know how others will use my library and how they do exception handling. And at that point I just ask myself: "*Why should I add a layer of abstraction when I simply pass everything to the new class?*". I would at least use the `raise X from Y` syntax, as the caller has then access to the origin traceback.

Python also has some topics about that in [PEP8](https://www.python.org/dev/peps/pep-0008/):

- Use exception chaining appropriately. In Python 3, "raise X from Y" should be used to indicate explicit replacement **without losing the original traceback**.
- When deliberately replacing an inner exception (using "raise X" in Python 2 or "raise X from None" in Python 3.3+), ensure that relevant details are transferred to the new exception (such as preserving the attribute name when converting KeyError to AttributeError, or embedding the text of the original exception in the new exception message).

Finally: That's just my two cents and there are other ways to do it :)
