### ISSUE TITLE
Invalid Content Type

### ISSUE THREAD

**Issue by ColinRobbins** [balloob/aiohue#22]
I am seeing the following error, using this component in HomeAssistant...
```
2020-01-01 19:17:17 ERROR (MainThread) [homeassistant.components.hue.light] Unable to reach bridge 192.168.10.17 (Invalid content type: text/html)
```

The error is caused by `python3.7/site-packages/aiohue/bridge.py` at line 62 it has
```
            async with self.websession.request(method, url, json=json) as res:
                if res.content_type != 'application/json':
                    raise ResponseError(
                        'Invalid content type: {}'.format(res.content_type))
```
looking at the URL it is calling...
``` 
http://xx.xx.xx.xx/api/<apikey>/lights/
```
or variations of.
This returns a type
```
text/html
```
although the content is JSON formatted.
Thus the error is thrown.

I don't know enough about what is happening here, but if the content is JSON formatted, back from Hue, why is the test rejecting it due to it being text/html.

I running hue version 3.33.0.

**Comment by balloob** [comment]
Can you print the content to make sure it's JSON ?

**Comment by ColinRobbins** [comment]
Hello,
Not quite sure how to print the content.
I modified the error call to
```
    raise ResponseError( 'Invalid content type: {}'.format(res.content_type) + "url:" + url )
```
Then I pasted the URL into a browser, and it gives...
{"1":{"name":"Hall","lights":["1"],"sensors":[],"type":"Room","state":{"all_on":false,"any_on":false},"recycle":false,"class":"Hallway","action":
....
```
which is valid JSON text.

I can be certain this is what the code is seeing, but it would seem likely.  I did try
```
    raise ResponseError( 'Invalid content type: {}'.format(res.content_type) + "url:" + url + " res:" res.content)
```
but it complained
```
can only concatenate str (not "StreamReader") to str
```

**Comment by balloob** [comment]
Add `print(await res.text())` before `raise` on line 70

**Comment by ColinRobbins** [comment]
Sorry, have not forgotten this, am still trying to get the info.
The problem is intermittent, so by the time I get to look the print output is long gone.
Will convert it to a logger statement and try again this weekend.

**Comment by ColinRobbins** [comment]
Finally trapped an instance of the error...

```
Unable to reach bridge 192.168.10.42 (Invalid content type: text/html)

<html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
So it seems like the Hue is dropping an error.
Not really sure why.  
In the first case, perhaps the error need to be handle better in HA?

Colin.

**Comment by balloob** [comment]
We should probably raise on invalid status before raising on content type.
