### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by bachp** [balloob/aiohue#5]
I think the component is meant to be licensed under [Apache-2.0](https://spdx.org/licenses/Apache-2.0.html), however I couldn't find a license file anywhere.

Please add a license file so it is clear what license is used.

**Comment by balloob** [comment]
Fixed in 7d807c2a782352ac2f24dda5af2914236fcbf508. Is Siemens using Home Assistant?

**Comment by bachp** [comment]
@balloob Thanks. We did some experiments with Home Assistant on embeded devices some time back. This is also the origin of the [meta-homeassistant](https://github.com/bachp/meta-homeassistant). But this has not been perused further. I'm still trying to update the layer in my spare time tough but it is hard due to the fast pace of Home Assistant development ;-).

**Comment by balloob** [comment]
If Siemens is planning on pursuing it further in the future, let me know. I'm working on setting up a partner program for Home Assistant to get official integrations going.
